// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

// Debug: verify env values at runtime
if (typeof window !== 'undefined') {
  const keyPreview = SUPABASE_PUBLISHABLE_KEY ? SUPABASE_PUBLISHABLE_KEY.slice(0, 8) + '...' : 'undefined';
  // eslint-disable-next-line no-console
  console.log('[Supabase] URL:', SUPABASE_URL);
  // eslint-disable-next-line no-console
  console.log('[Supabase] Anon key present:', !!SUPABASE_PUBLISHABLE_KEY, keyPreview);
}

// Import the supabase client like this:
// import { supabase } from "/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Let supabase-js manage headers automatically (apikey + user access token)
  // Removing the hard-coded Authorization header prevents overriding user identity
});